apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: session-coordination
  labels:
    app: session-coordination
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: session-coordination-port
  selector:
    app: session-coordination
    release: {{ .Release.Name }}

